name: pilot-development

channels:
  - conda-forge
  - defaults

dependencies:
  # runtime
  - python =3.9
  - pip
  - requests
  # testing and development
  - pycodestyle
  - coverage
  - mock
  - pylint
  - pytest
  - pytest-mock
  - shellcheck
